var name1 , name2;
name1 = "sweety";
name2 = "cutie";
console.log("Before Swap : Name1 -" ,name1,", Name2 -", name2);
var temp = name1;
name1 = name2;
name2 = temp;
console.log("After Swap : Name1-" ,name1,", Name2 -", name2);
console.log("-----------------------------------------------------------------");
var num1,num2,num3;
num1 = "100";
num2 = "200";
num3 = "300";
console.log("Before Swap : num1 -",num1," ,num2 -",num2," ,num3 -",num3);
var temp =num1;
num1 =num2;
num2 =num3;
num3 = temp;
console.log("After Swap : num1 -" ,num1,",num2 -",num2,",num3 -",num3);

