var bankName;
console.log("Befor initialization  :"   +bankName );
var  bankName = "SBI Bank";
console.log("After initialization  :"   + bankName );
var dataType = "String";
console.log("Data Type             :"   + dataType );
console.log("------------------------------------------------------------------------------------");
var marks = "90%";
console.log( "Marks                 :"  + marks);
var dataType = "90%";
console.log("Data Type is           :"  +   typeof dataType );
console.log("------------------------------------------------------------------------------------");
var isWorking;
console.log("Befor initialization   :"  +isWorking );
var isWorking = "True";
console.log("After initialization   :"  +isWorking );
var isWorking = true;
var dataType;
console.log( "dataType   :" +typeof isWorking );
console.log("---------------------------------------------------------------------------------------");
var totalCount = "107";
console.log( "Total Value :" + totalCount);
var totalCount;
console.log("Data Type :    "+typeof totalCount);
var totalCount = 107;
console.log("Value is :  "+  totalCount);
var totalCount = 107;
console.log("After Updation :  "+ typeof totalCount);
